Src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Src/objects/Student__c.object
<CustomObject>
    <description>Custom objects for students</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>College_Fees__c</fullName>
        <label>College Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_and_Time__c</fullName>
        <description>Student records filled Date and Time</description>
        <label>Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Student Date of birth</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exame_fees__c</fullName>
        <label>Exame fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Indian_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indian Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nick_Name__c</fullName>
        <label>Nick Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG_percentage__c</fullName>
        <label>PG percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                    <default>true</default>
                    <label>Madhya Pradesh</label>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Uttar Pradesh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Details__c</fullName>
        <label>Student Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Student Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Phone_Number__c</fullName>
        <inlineHelpText>Enter student Mobile Number</inlineHelpText>
        <label>Student Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Student_linkdin_Id__c</fullName>
        <label>Student linkdin Id</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student Details</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Src/classes/StudentInfo.cls
public class StudentInfo {
        public static void infoStudent(){
        Student__c student = new Student__c();
        student.Name = 'Abhishek Pawar';
        student.Nick_Name__c = 'Abhishek';
        student.Date_of_Birth__c = Date.newInstance(2022, 06, 07) ;
        student.Date_and_Time__c = DateTime.newInstanceGmt(2022, 06, 07, 17, 20, 32);
        student.Student_Phone_Number__c = '9893030346' ;
        student.Student_Email__c = 'abhishekpawar@gmail.com';
        student.Student_linkdin_Id__c = 'https://www.youtube.com/' ;
        student.Roll_Number__c = 170240420;
        student.City__c = 'Bhopal';
        student.Address__c = 'Bhopal';
        student.Student_Details__c = 'college Student';
        student.Time__c = Time.newInstance(17, 17, 17, 17);
        student.Exame_fees__c  = 2000;
        student.College_Fees__c = 40000;
        student.PG_percentage__c = 90;
        student.Country__c = 'India';
        student.State__c = 'Madhya Pradesh' ;
        student.Indian_Student__c = true;
        student.Bank_Account_Number__c = '7894563217';
        insert student;
        
    } 

}