Src/objects/Student__c.object
<CustomObject>
    <description>Custom objects for students</description>
    <fields>
        <fullName>Nick_Name__c</fullName>
        <label>Nick Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Student Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Phone_Number__c</fullName>
        <inlineHelpText>Enter student Mobile Number</inlineHelpText>
        <label>Student Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student Details</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Src/classes/StudentDebugQuery.cls
public class StudentDebugQuery {
    public StudentDebugQuery(){
        Student__c student1 = [SELECT ID, Name, Student_Email__c FROM Student__c ORDER BY createdDate DESC LIMIT 1];
        system.debug('Check Student Data' + student1);
        
        List<Student__c> StudentList = [SELECT ID, Roll_Number__c, Student_Email__c, Student_Phone_Number__c, Nick_Name__c FROM Student__c ORDER BY CreatedDate DESC LIMIT 5];
        for(Student__c student : StudentList){
        	system.debug('Check Student Data :::' + studentList);
        }

    }

}